version: 2.1

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:latest  # Use the latest Cloud SDK image
    steps:
      - checkout
      # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable
      - run:
          name: Set Google Cloud service account key
          command: |
            echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/gcp-key.json
            export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp-key.json"

      # activate SA for gcloud
      - run: |
          gcloud auth activate-service-account --key-file="/tmp/gcp-key.json"

      # Function specific details (replace with your configuration)
      - run: |
          PROJECT=latam-challenge-421420
          FUNCTION_NAME=get_flights
          REGION=southamerica-west1
          ENTRYPOINT=get_flights
          RUNTIME=python39
          SOURCE=./cloud_function
          gcloud functions deploy $FUNCTION_NAME \
              --gen2 \
              --project $PROJECT \
              --region $REGION \
              --runtime $RUNTIME \
              --trigger-http \
              --entry-point $ENTRYPOINT \
              --allow-unauthenticated \
              --service-account cf-deployer-sa@latam-challenge-421420.iam.gserviceaccount.com \
              --source=$SOURCE

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
